// app/api/admin/register-member/route.js
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey);

export async function POST(request) {
  try {
    const contentType = request.headers.get("content-type");
    const isFormData = contentType?.includes("multipart/form-data");

    let full_name, address, phone, whatsapp, messenger, lga, ward, polling_unit;
    let date_of_birth, gender, profile_image;

    if (isFormData) {
      const formData = await request.formData();
      full_name = formData.get("full_name");
      address = formData.get("address");
      phone = formData.get("phone");
      whatsapp = formData.get("whatsapp");
      messenger = formData.get("messenger") || null;
      lga = formData.get("lga");
      ward = formData.get("ward");
      polling_unit = formData.get("polling_unit");
      date_of_birth = formData.get("date_of_birth");
      gender = formData.get("gender");
      profile_image = formData.get("profile_image");
    } else {
      const body = await request.json();
      full_name = body.full_name;
      address = body.address;
      phone = body.phone;
      whatsapp = body.whatsapp;
      messenger = body.messenger || null;
      lga = body.lga;
      ward = body.ward;
      polling_unit = body.polling_unit;
      date_of_birth = body.date_of_birth || null;
      gender = body.gender || null;
      profile_image = null;
    }

    // Validate required fields
    if (
      !full_name ||
      !address ||
      !phone ||
      !whatsapp ||
      !lga ||
      !ward ||
      !polling_unit
    ) {
      return Response.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Validate age if date_of_birth is provided (must be 18+)
    if (date_of_birth) {
      const birthDate = new Date(date_of_birth);
      const today = new Date();
      const age = today.getFullYear() - birthDate.getFullYear();
      const monthDiff = today.getMonth() - birthDate.getMonth();

      if (
        age < 18 ||
        (age === 18 && monthDiff < 0) ||
        (age === 18 && monthDiff === 0 && today.getDate() < birthDate.getDate())
      ) {
        return Response.json(
          { error: "Member must be at least 18 years old" },
          { status: 400 }
        );
      }
    }

    let profile_image_url = null;

    // Upload image if provided
    if (profile_image && profile_image.size > 0) {
      try {
        const MAX_FILE_SIZE = 5 * 1024 * 1024;
        if (profile_image.size > MAX_FILE_SIZE) {
          return Response.json(
            { error: "Image size must be less than 5MB" },
            { status: 400 }
          );
        }

        const allowedTypes = ["image/jpeg", "image/png", "image/webp"];
        if (!allowedTypes.includes(profile_image.type)) {
          return Response.json(
            { error: "Only JPEG, PNG, and WebP images are allowed" },
            { status: 400 }
          );
        }

        const fileExt = profile_image.name.split(".").pop();
        const fileName = `${Date.now()}-${Math.random()
          .toString(36)
          .substring(7)}.${fileExt}`;
        const filePath = `${lga}/${fileName}`;

        const arrayBuffer = await profile_image.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        const { data: uploadData, error: uploadError } =
          await supabaseAdmin.storage
            .from("members-images")
            .upload(filePath, buffer, {
              contentType: profile_image.type,
              upsert: false,
            });

        if (uploadError) {
          console.error("Image upload error:", uploadError);
          return Response.json(
            { error: "Failed to upload image: " + uploadError.message },
            { status: 400 }
          );
        }

        const { data: urlData } = supabaseAdmin.storage
          .from("members-images")
          .getPublicUrl(filePath);

        profile_image_url = urlData.publicUrl;
      } catch (imgErr) {
        console.error("Image processing error:", imgErr);
        return Response.json(
          { error: "Failed to process image: " + imgErr.message },
          { status: 400 }
        );
      }
    }

    // Prepare member data (membership_number will be auto-generated by trigger)
    const memberData = {
      full_name,
      address,
      phone,
      whatsapp,
      messenger,
      lga,
      ward,
      polling_unit,
    };

    if (date_of_birth) memberData.date_of_birth = date_of_birth;
    if (gender) memberData.gender = gender;
    if (profile_image_url) memberData.profile_image_url = profile_image_url;

    // Insert member data
    const { data, error } = await supabaseAdmin
      .from("members")
      .insert([memberData])
      .select()
      .single();

    if (error) {
      console.error("Database insert error:", error);

      if (profile_image_url) {
        try {
          const filePath = profile_image_url.split("/members-images/")[1];
          await supabaseAdmin.storage.from("members-images").remove([filePath]);
        } catch (cleanupErr) {
          console.error("Image cleanup error:", cleanupErr);
        }
      }

      return Response.json(
        { error: error.message || "Failed to register member" },
        { status: 400 }
      );
    }

    return Response.json({ success: true, data }, { status: 200 });
  } catch (err) {
    console.error("Registration error:", err);
    return Response.json(
      { error: "Internal server error: " + err.message },
      { status: 500 }
    );
  }
}
